Add check to limit number of strict ts-errors

diff --git a/.github/workflows/app-frontend-unit-tests.yml b/.github/workflows/app-frontend-unit-tests.yml
--- a/.github/workflows/app-frontend-unit-tests.yml
+++ b/.github/workflows/app-frontend-unit-tests.yml
@@ -49,6 +49,16 @@ jobs:
       - name: type-check
         run: yarn tsc
 
+      - name: type-check-strict
+        run: |
+          strict_error_count="$(yarn tsc-strict:error-count)"
+          echo "Strict TypeScript error count: ${strict_error_count}"
+
+          if (( strict_error_count >= 306 )); then
+            echo "Strict TypeScript error count is ${strict_error_count}, expected less than 306."
+            exit 1
+          fi
+
       - name: run eslint
         run: yarn lint
 
